version: "{build}"
clone_depth: 1
image: Visual Studio 2019

build_script:
- cmd: call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat" x86_amd64
- cmd: scripts\lua.exe make.lua release > build.ninja
- cmd: scripts\ninja.exe -v -k 0
- cmd: scripts\ducible.exe release\cocainediesel.exe
- cmd: scripts\ducible.exe release\elevate_for_update.exe
- cmd: scripts\ducible.exe release\headlessupdater.exe
- cmd: "C:\\Program Files (x86)\\NSIS\\makensis.exe" -DONLY_WRITE_UNINSTALLER installer\installer.nsi
- cmd: installer\CocaineDieselInstaller.exe /S
- cmd: "C:\\Program Files (x86)\\NSIS\\makensis.exe" installer\installer.nsi

artifacts:
- path: installer/CocaineDieselInstaller.exe
- path: release
  name: launcher_windows
