version: "{build}"
clone_depth: 1
image: Ubuntu

build_script:
- sh: sudo apt-get -y update
- sh: sudo apt-get -y install lua5.3
- sh: make -j$(nproc --all) release

artifacts:
- path: source/build
  name: cocaine_diesel_linux
