version: "{build}"
clone_depth: 1
image: Ubuntu

build_script:
- sh: sudo apt-get -y update
- sh: sudo apt-get -y install libxcursor-dev libxi-dev libxrandr-dev libxinerama-dev libegl1-mesa-dev libxkbcommon-dev libgl-dev
- sh: scripts/lua.linux make.lua release > build.ninja
- sh: scripts/ninja.linux

artifacts:
- path: release
  name: cocaine_diesel_linux
