version: "{build}"
clone_depth: 1
image: Ubuntu

build_script:
- sh: scripts/lua.linux make.lua release > build.ninja
- sh: scripts/ninja.linux

artifacts:
- path: release
  name: cocaine_diesel_linux
